config/routes.rb
Rails.application.routes.draw do

  devise_for :members, :controllers => {
    :registrations => "members/registrations",
    :sessions => "members/sessions",
    :passwords => "members/passwords",
    :confirmations => "members/confirmations"
  }

  devise_scope :member do
    get 'sign_up', to: "members/registrations#new"
    get 'sign_in', to: "members/sessions#new"
    delete 'sign_out', to: "members/sessions#destroy"
  end

	resources :home
	resources :members

  root 'home#index'

end

app/views/layouts/_contactfields.html.erb
<%= f.fields_for :member_contacts do |contact|%>

  <% if !@contactInfo["avatar"].blank? %>
    <%= image_tag @contactInfo.avatar_url(:medium).to_s, :class=>"profilePhoto" %>
  <% end %>
  <div class="photoPreview">
    <i class="fa fa-upload photoUpload"></i>
    <p id="uploadClick">Click to Upload</p>
  </div>

  <%= contact.file_field :avatar, accept: 'image/png,image/gif,image/jpeg, image/jpg', id: 'uploadAvatar' %>
  <p class="deletePhoto">Delete</p>

  <%= contact.text_field :email, placeholder: "Email", :class => "form-control", readonly: true %>

  <%= contact.fields_for :typ_countries do |country|%>
    <%= country.collection_select :id, TypCountry.order(:id),:id,:country, {prompt: "請選擇縣市", selected: @contactInfo["typ_country_id"] }, {:class => "form-control"} %>
  <% end %>

  <%= contact.fields_for :typ_regions do |region|%>
    <%= region.grouped_collection_select :id, TypCountry.order(:country),:typ_regions, :country, :id, :name, {prompt: "請選擇鄉鎮市區", selected: @contactInfo["typ_region_id"] }, {:class => "form-control"}%>
  <% end %>

  <%= contact.text_field :postal_code, placeholder: "郵遞區號", :class => "form-control" %>
  <%= contact.text_field :address1, placeholder: "詳細地址", :class => "form-control" %>

  <%= contact.text_field :cell_number, placeholder: "手機電話", :class => "form-control" %>
  <%= contact.hidden_field :member_id, value: current_member.id %>

<% end %>

app/views/layouts/_footer.html.erb
<div id="push"></div>
<footer class="footer navbar-fixed-bottom">
  <div class="container">
    <nav>
      <ul>
        <!--li><%= link_to "About", "#" %></li>
        <li><%= link_to "Fee Guide", "#" %></li-->
        <li><%= link_to "Contact Us", "#" %></li>
        <li><%= link_to "Terms of Use", "#" %></li>
        <li><%= link_to "Privacy Policy", "#" %></li>
        <li><%= link_to "How it Works?", "#" %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" >
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">台灣內苑佛教文化學會</span>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= yield(:index) %>"><%= link_to "首頁", root_path %></li>
        <li class="<%= yield(:about) %>"><%= link_to "關於內苑", "#" %></li>
        <li class="<%= yield(:news) %>"><%= link_to "最新訊息", "#" %></li>
        <li class="<%= yield(:course) %>"><%= link_to "開課訊息", "#" %></li>
        <li class="<%= yield(:activityphoto) %>"><%= link_to "活動剪影", "#" %></li>
        <li class="<%= yield(:faq) %>"><%= link_to 'FAQs', "#" %></li>
        <li class="<%= yield(:post) %>"><%= link_to "Blog", "#" %></li>
        <li class="<%= yield(:forum) %>"><%= link_to "Forum", "#" %></li>
        <li class="<%= yield(:links) %>"><%= link_to "好站相連", "#" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>  會員 <i class="fa fa-chevron-down"></i></a>
          <ul class="dropdown-menu">
            <% if signed_in? %>
              <li class="<%= yield(:edit_profile) %>"><%=  link_to "我的檔案", edit_member_path(current_member) %></li>
              <li class="divider"></li>
              <li><%= link_to "登出", sign_out_path, method: :delete %></li>
            <% else %>
              <li class="<%= yield(:register) %>"><%= link_to "註冊", sign_up_path %></li>
              <li class="<%= yield(:login) %>"><%= link_to "登入", sign_in_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<% if signed_in? %>
<div class="col-sm3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li class="sidebar_overview"><%= link_to "聯絡方式", edit_member_path(current_member) %></li>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><%= yield(:title) %> | Buddhism</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% render 'layouts/shim' %>
</head>
<body class="<%= controller_name %> <%= action_name %>" >
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> col-md-8 col-md-offset-2 main"><%= value %></div>
    <% end %>
    <div class="row">
      <%= yield :sidebar %>
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>